default:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: IOFRMBT-RE79037
      user: vijay
      database: analytics
      warehouse: transforming
      schema: dbt_vijay
      password: SnowVij@y250287
      role: 
